---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PRODUCT:

inputs:
  - name: vs-tile-pipelines

run:
  path: vs-tile-pipelines/tasks/delete-product/task.sh
