---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: "rjain/buildbox"

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PRODUCT:

inputs:
  - name: vs-tile-pipelines
  - name: tool-om

run:
  path: vs-tile-pipelines/tasks/delete-product/task.sh
