---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: "rjain/buildbox"

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  SINGLETON_JOB_AZ:
  OTHER_JOB_AZS:
  NETWORK_NAME:
  NOTIFICATIONS_EMAIL:

inputs:
  - name: vs-pcf-pipelines
  - name: tool-om

run:
  path: vs-pcf-pipelines/tasks/config-pcf-metrics/task.sh
