---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PIVNET_API_TOKEN:
  NO_PROXY:
  OM_IP:
  IAAS:

inputs:
  - name: pivnet-product
  - name: vs-tile-pipelines

run:
  path: vs-tile-pipelines/tasks/upload-product-and-stemcell/task.sh
