---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PIVNET_API_TOKEN:
  NO_PROXY:
  OM_IP:
  IAAS:
  PASWINDOWS:

inputs:
  - name: tool-om
  - name: pivnet-product
  - name: vs-tile-pipelines
  - name: windows-stemcell

run:
  path: vs-tile-pipelines/tasks/upload-wrt-and-stemcell/task.sh
